version: 2

jobs:

  test:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.9.5
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
        environment:
          JUGGLE_EMAIL_BACKEND: django.core.mail.backends.dummy.EmailBackend
          JUGGLE_SECRET_KEY: stub
          JUGGLE_USE_SENTRY: off
          JUGGLE_DEBUG: off
          JUGGLE_DATABASE_URL: postgresql://postgres:test_db_password@localhost/juggle_test_db
          JUGGLE_CELERY_BROKER: redis://localhost:6379/1
          JUGGLE_CELERY_TASK_ALWAYS_EAGER: on
      - image: postgres:13.3
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
        environment:
          POSTGRES_DB: juggle_test_db
          POSTGRES_PASSWORD: test_db_password
      - image: redis:6.2.4
        auth:
          username: $DOCKERHUB_USER
          password: $DOCKERHUB_PASS
    steps:
      - checkout
      - restore_cache:
          key: python-deps-v1-{{ checksum "api/requirements-dev.txt" }}
      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv .env
            . .env/bin/activate
            pip install -U pip
            pip install -r api/requirements-dev.txt
      - save_cache:
          key: python-deps-v1-{{ checksum "api/requirements-dev.txt" }}
          paths:
            - ".env"
      - run:
          name: Check `black`
          command: . .env/bin/activate && fab test.black
      - run:
          name: Check `isort`
          command: . .env/bin/activate && fab test.isort
      - run:
          name: Check `pylama`
          command: . .env/bin/activate && fab test.pylama
      - run:
          name: Check `bandit`
          command: . .env/bin/activate && fab test.bandit
      - run:
          name: Check `safety`
          command: . .env/bin/activate && fab test.safety
      - run:
          name: Check `pylint`
          command: . .env/bin/activate && fab test.pylint
      - run:
          name: Wait for Redis
          command: dockerize -wait tcp://localhost:6379 -timeout 1m
      - run:
          name: Wait for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Check for uncreated migrations
          command: |
            . .env/bin/activate
            ./api/manage.py makemigrations --check --dry-run
      - run:
          name: Run tests
          command: |
            . .env/bin/activate
            ./api/manage.py collectstatic --no-input
            fab test.run
      - store_test_results:
          path: ~/project/api/test-results

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
